apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: trivy
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.21.0"
    tekton.dev/categories: Security
    tekton.dev/tags: Security
spec:
  description: >-
    Vulnerability scanner with Trivy:
    This will scan vulnerability in Containers.
  params:
  - name: IMAGE
    description: Reference of the image Trivy will scan.
  - name: IMAGE_DIGEST
    description: Reference of the image digest Trivy will scan.
  - name: TRIVY_IMAGE
    description: The location of the Trivy scan image.
    default: aquasec/trivy:0.41.2
  - name: TRIVY_USERNAME
    description: Authentication user name to get the target scan image.
    default: ""
  - name: TRIVY_PASSWORD
    description: Authentication password to get the target scan image.
    default: ""
  workspaces:
  - name: cache
  stepTemplate:
    env:
    - name: TRIVY_USERNAME
      value: $(params.TRIVY_USERNAME)
    - name: TRIVY_PASSWORD
      value: $(params.TRIVY_PASSWORD)
  steps:
  - name: build-report
    image: $(params.TRIVY_IMAGE)
    script: |
      SCAN_CONTAINER_IMAGE=$(params.IMAGE)
      trivy --cache-dir=$(workspaces.cache.path)/trivy \
        image --timeout 10m --exit-code=0 --severity=HIGH,CRITICAL \
        ${SCAN_CONTAINER_IMAGE}
  - name: severe-vulnerabilities
    image: $(params.TRIVY_IMAGE)
    script: |
      SCAN_CONTAINER_IMAGE=$(params.IMAGE)
      trivy --cache-dir=$(workspaces.cache.path)/trivy \
        image --exit-code=1 --no-progress --severity=CRITICAL \
        ${SCAN_CONTAINER_IMAGE}

